feat(installation): add coc-clangd and nvim builtin LSP client
llvm/clangd-www pull request #103
Opened 2024-07-08 11:08 UTC by fannheyward

Closes #90 #94

2024-07-08 11:13 UTC, fannheyward commented
cc @HighCommander4

2024-07-12 05:45 UTC, HighCommander4 requested changes
Thanks for the patch!

2024-07-12 05:45 UTC, HighCommander4 commented on installation.md
> +clangd runs through [Language Server Protocol](https://microsoft.github.io/language-server-protocol/),
This line, "clangd runs through the Language Server Protocol", is applicable to all editors. Let's move it up to the beginning of the "Editor plugins" section.

2024-07-12 05:45 UTC, HighCommander4 commented on installation.md
> +You can also use [clangd_extensions.nvim](https://github.com/p00f/clangd_extensions.nvim) directly, with more off-spec features support.
Neat, I didn't know about this

2024-07-12 05:45 UTC, HighCommander4 commented on installation.md
> +2. enable clangd in your init.lua: `require'lspconfig'.clangd.setup{}`
It would be great to have some more details about how to add arguments, and how to get logs, but this can be left for a future PR

2024-07-14 04:45 UTC, HighCommander4 approved these changes
Thank you!

2024-07-14 04:45 UTC, HighCommander4 commented on installation.md
> +supports LSP can communicate with clangd to provide features like code completion, diagnostics, go-to-definition, etc.
nit: supports --> support

2024-07-14 04:45 UTC, HighCommander4 commented on installation.md
> +There're two ways to get request/response logs from coc-clangd:
nit: There're --> There are

2024-07-14 06:06 UTC, merged