Update rename feature for 11 release.
llvm/clangd-www pull request #23
Opened 2021-02-11 13:55 UTC by hokein

2021-02-12 18:29 UTC, kirillbobyrev approved these changes
Thanks!

2021-02-12 22:51 UTC, njames93 reviewed
Isn't it wise to specify that the default behaviour of being enabled is only for clangd-11 and later. We still want the documentation to make sense for people using an older version of clangd. Users of clangd-10 may be confused as to why they aren't getting cross-file rename without specifying the flag, even though the website says it should work.

2021-02-13 12:57 UTC, kirillbobyrev commented
uh, I actually didn't think about it, very good point, thanks!

2021-02-16 12:57 UTC, kirillbobyrev requested changes

2021-02-16 12:57 UTC, kirillbobyrev commented on features.md
> +`-cross-file-rename=false`.
so, basically, do `{:.v11}` and new thing and just keep the existing one as is at the bottom?

2021-02-16 12:57 UTC, kirillbobyrev commented on features.md
> +This default mode allows renaming symbols used in several files.
same here.

2021-02-27 21:41 UTC, sam-mccall commented
We're about to hit v12. I think the priorities are:

1. document the behavior of current versions
2. hint when older versions might behave differently
3. document the behavior of older versions

If keeping old descriptions around is be invasive to the flow of text, I don't think we should do it - it sacrifices priority 1 to achieve priority 3.

2021-04-23 11:36 UTC, merged